coverage:
  status:
    project:
      rtl:
        paths:
          - ReflectionTemplateLib/rtl
        target: 85%
        informational: true

comment:
  layout: "diff, flags, files"
  behavior: default

ignore:
  - "demo/**"
  - "RTLBenchmarkApp/**"