
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#pragma once
#include <vector>

#include "rtl_builder.h"


namespace regs7::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs10::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs1::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs1::type1 {
    void init(std::vector<rtl::Function>&);
}


namespace regs1::type2 {
    void init(std::vector<rtl::Function>&);
}


namespace regs0::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs3::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs2::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs4::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs5::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs6::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::type1 {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::type2 {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::type3 {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::type4 {
    void init(std::vector<rtl::Function>&);
}


namespace regs9::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs11::type0 {
    void init(std::vector<rtl::Function>&);
}

