/*****************************************************************************
 *                                                                           *
 *  clang-mirror Generated Reflection Surface                                *
 *                                                                           *
 *  This file is automatically generated by clang-mirror and represents      *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library (RTL).                                       *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection, enabling         *
 *  compiler checking and IDE integration.                                   *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *                                                                           *
 *  SPDX-License-Identifier: MIT                                             *
 *                                                                           *
 *****************************************************************************/


#pragma once
#include <string_view>


namespace rtcl {

namespace function {
namespace complex {
    inline constexpr std::string_view getMagnitude = "complex::getMagnitude";
}}

namespace function {
namespace complex {
    inline constexpr std::string_view setReal = "complex::setReal";
}}

namespace function {
namespace complex {
    inline constexpr std::string_view setImaginary = "complex::setImaginary";
}}

namespace function {
    inline constexpr std::string_view getComplexNumAsString = "getComplexNumAsString";
}

namespace function {
    inline constexpr std::string_view reverseString = "reverseString";
}

namespace function {
    inline constexpr std::string_view revStrConstRefArg = "revStrConstRefArg";
}

namespace function {
    inline constexpr std::string_view revStrRValueRefArg = "revStrRValueRefArg";
}

namespace function {
    inline constexpr std::string_view revStrNonConstRefArg = "revStrNonConstRefArg";
}

namespace function {
    inline constexpr std::string_view revStrOverloadValCRef = "revStrOverloadValCRef";
}

namespace function {
    inline constexpr std::string_view revStrOverloadValRef = "revStrOverloadValRef";
}

namespace function {
    inline constexpr std::string_view revStrOverloadRefAndCRef = "revStrOverloadRefAndCRef";
}

namespace type {
namespace nsdate {
namespace Calender {
    inline constexpr std::string_view id = "nsdate::Calender";
}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view Calender = "Calender";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view create = "create";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view getSavedDate = "getSavedDate";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view getTheDate = "getTheDate";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view getSavedEvent = "getSavedEvent";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view getTheEvent = "getTheEvent";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view instanceCount = "instanceCount";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view getMoveOpsCount = "getMoveOpsCount";
}}}}

namespace type {
namespace nsdate {
namespace Calender {
namespace method {
    inline constexpr std::string_view resetMoveOpsCounter = "resetMoveOpsCounter";
}}}}


namespace type {
namespace StrWrapB {
    inline constexpr std::string_view id = "StrWrapB";
}}

namespace type {
namespace StrWrapB {
namespace method {
    inline constexpr std::string_view StrWrapB = "StrWrapB";
}}}


namespace type {
namespace nsdate {
namespace Event {
    inline constexpr std::string_view id = "nsdate::Event";
}}}

namespace type {
namespace nsdate {
namespace Event {
namespace method {
    inline constexpr std::string_view instanceCount = "instanceCount";
}}}}

namespace type {
namespace nsdate {
namespace Event {
namespace method {
    inline constexpr std::string_view getEventDate = "getEventDate";
}}}}

namespace type {
namespace nsdate {
namespace Event {
namespace method {
    inline constexpr std::string_view reset = "reset";
}}}}


namespace type {
namespace nsdate {
namespace Date {
    inline constexpr std::string_view id = "nsdate::Date";
}}}

namespace type {
namespace nsdate {
namespace Date {
namespace method {
    inline constexpr std::string_view Date = "Date";
}}}}

namespace type {
namespace nsdate {
namespace Date {
namespace method {
    inline constexpr std::string_view instanceCount = "instanceCount";
}}}}

namespace type {
namespace nsdate {
namespace Date {
namespace method {
    inline constexpr std::string_view getAsString = "getAsString";
}}}}

namespace type {
namespace nsdate {
namespace Date {
namespace method {
    inline constexpr std::string_view updateDate = "updateDate";
}}}}


namespace type {
namespace StrMute {
    inline constexpr std::string_view id = "StrMute";
}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view reverseString = "reverseString";
}}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view revStrConstRefArg = "revStrConstRefArg";
}}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view revStrRValueRefArg = "revStrRValueRefArg";
}}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view revStrNonConstRefArg = "revStrNonConstRefArg";
}}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view revStrOverloadValCRef = "revStrOverloadValCRef";
}}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view revStrOverloadValRef = "revStrOverloadValRef";
}}}

namespace type {
namespace StrMute {
namespace method {
    inline constexpr std::string_view revStrOverloadRefAndCRef = "revStrOverloadRefAndCRef";
}}}


namespace type {
namespace StrStatic {
    inline constexpr std::string_view id = "StrStatic";
}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view reverseString = "reverseString";
}}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view revStrConstRefArg = "revStrConstRefArg";
}}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view revStrRValueRefArg = "revStrRValueRefArg";
}}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view revStrNonConstRefArg = "revStrNonConstRefArg";
}}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view revStrOverloadValCRef = "revStrOverloadValCRef";
}}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view revStrOverloadValRef = "revStrOverloadValRef";
}}}

namespace type {
namespace StrStatic {
namespace method {
    inline constexpr std::string_view revStrOverloadRefAndCRef = "revStrOverloadRefAndCRef";
}}}


namespace type {
namespace Book {
    inline constexpr std::string_view id = "Book";
}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view Book = "Book";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view setAuthor = "setAuthor";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view getTitle = "getTitle";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view addCopyrightTag = "addCopyrightTag";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view setDescription = "setDescription";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view getPublishedOn = "getPublishedOn";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view getInstanceCount = "getInstanceCount";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view updateBookInfo = "updateBookInfo";
}}}

namespace type {
namespace Book {
namespace method {
    inline constexpr std::string_view addPreface = "addPreface";
}}}


namespace type {
namespace StrWrapD {
    inline constexpr std::string_view id = "StrWrapD";
}}

namespace type {
namespace StrWrapD {
namespace method {
    inline constexpr std::string_view StrWrapD = "StrWrapD";
}}}


namespace type {
namespace Person {
    inline constexpr std::string_view id = "Person";
}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view getFirstName = "getFirstName";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view Person = "Person";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view getInstanceCount = "getInstanceCount";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view updateAddress = "updateAddress";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view getDefaults = "getDefaults";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view getProfile = "getProfile";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view createConst = "createConst";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view createPtr = "createPtr";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view deletePtr = "deletePtr";
}}}

namespace type {
namespace Person {
namespace method {
    inline constexpr std::string_view updateLastName = "updateLastName";
}}}


namespace type {
namespace StrConstOverload {
    inline constexpr std::string_view id = "StrConstOverload";
}}

namespace type {
namespace StrConstOverload {
namespace method {
    inline constexpr std::string_view reverseString = "reverseString";
}}}


namespace type {
namespace Animal {
    inline constexpr std::string_view id = "Animal";
}}

namespace type {
namespace Animal {
namespace method {
    inline constexpr std::string_view Animal = "Animal";
}}}

namespace type {
namespace Animal {
namespace method {
    inline constexpr std::string_view getFamilyName = "getFamilyName";
}}}

namespace type {
namespace Animal {
namespace method {
    inline constexpr std::string_view setAnimalName = "setAnimalName";
}}}

namespace type {
namespace Animal {
namespace method {
    inline constexpr std::string_view setFamilyName = "setFamilyName";
}}}

namespace type {
namespace Animal {
namespace method {
    inline constexpr std::string_view getInstanceCount = "getInstanceCount";
}}}

namespace type {
namespace Animal {
namespace method {
    inline constexpr std::string_view updateZooKeeper = "updateZooKeeper";
}}}


namespace type {
namespace StrWrap {
    inline constexpr std::string_view id = "StrWrap";
}}

namespace type {
namespace StrWrap {
namespace method {
    inline constexpr std::string_view sstr = "sstr";
}}}

namespace type {
namespace StrWrap {
namespace method {
    inline constexpr std::string_view StrWrap = "StrWrap";
}}}


namespace type {
namespace StrWrapA {
    inline constexpr std::string_view id = "StrWrapA";
}}

namespace type {
namespace StrWrapA {
namespace method {
    inline constexpr std::string_view StrWrapA = "StrWrapA";
}}}


namespace type {
namespace StrWrapC {
    inline constexpr std::string_view id = "StrWrapC";
}}

namespace type {
namespace StrWrapC {
namespace method {
    inline constexpr std::string_view StrWrapC = "StrWrapC";
}}}


namespace type {
namespace StrConst {
    inline constexpr std::string_view id = "StrConst";
}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view reverseString = "reverseString";
}}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view revStrConstRefArg = "revStrConstRefArg";
}}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view revStrRValueRefArg = "revStrRValueRefArg";
}}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view revStrNonConstRefArg = "revStrNonConstRefArg";
}}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view revStrOverloadValCRef = "revStrOverloadValCRef";
}}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view revStrOverloadValRef = "revStrOverloadValRef";
}}}

namespace type {
namespace StrConst {
namespace method {
    inline constexpr std::string_view revStrOverloadRefAndCRef = "revStrOverloadRefAndCRef";
}}}


namespace type {
namespace Library {
    inline constexpr std::string_view id = "Library";
}}

namespace type {
namespace Library {
namespace method {
    inline constexpr std::string_view Library = "Library";
}}}

namespace type {
namespace Library {
namespace method {
    inline constexpr std::string_view getBookByTitle = "getBookByTitle";
}}}

namespace type {
namespace Library {
namespace method {
    inline constexpr std::string_view getInstanceCount = "getInstanceCount";
}}}

namespace type {
namespace Library {
namespace method {
    inline constexpr std::string_view getBooksCount = "getBooksCount";
}}}

namespace type {
namespace Library {
namespace method {
    inline constexpr std::string_view addBook = "addBook";
}}}


}