/*****************************************************************************
 *                                                                           *
 *  clang-mirror Generated Reflection Surface                                *
 *                                                                           *
 *  This file is automatically generated by clang-mirror and represents      *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library (RTL).                                       *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection, enabling         *
 *  compiler checking and IDE integration.                                   *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *                                                                           *
 *  SPDX-License-Identifier: MIT                                             *
 *                                                                           *
 *****************************************************************************/


#include "reg_ids.h"
#include "reg_decls.h"

#include "Book.h"
#include "Library.h"


namespace regs9::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<Library>(cxx::type::Library::id)
                                 .build());

        fns.push_back(rtl::type().member<Library>()
                                 .methodStatic(cxx::type::Library::fn::getBookByTitle::id)
                                 .build(&Library::getBookByTitle));

        fns.push_back(rtl::type().member<Library>()
                                 .methodStatic(cxx::type::Library::fn::getInstanceCount::id)
                                 .build(&Library::getInstanceCount));

        fns.push_back(rtl::type().member<Library>()
                                 .methodStatic(cxx::type::Library::fn::getBooksCount::id)
                                 .build(&Library::getBooksCount));

        fns.push_back(rtl::type().member<Library>()
                                 .methodStatic(cxx::type::Library::fn::addBook::id)
                                 .build(&Library::addBook));
    }
}

