/*****************************************************************************
 *                                                                           *
 *  clang-mirror Generated Reflection Surface                                *
 *                                                                           *
 *  This file is automatically generated by clang-mirror and represents      *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library (RTL).                                       *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection, enabling         *
 *  compiler checking and IDE integration.                                   *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *                                                                           *
 *  SPDX-License-Identifier: MIT                                             *
 *                                                                           *
 *****************************************************************************/


#include "reg_ids.h"
#include "reg_decls.h"

#include "StringConstOverload.h"


namespace regs6::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<StrConstOverload>(cxx::type::StrConstOverload::id)
                                 .build());

        fns.push_back(rtl::type().member<StrConstOverload>()
                                 .method<void>(cxx::type::StrConstOverload::fn::reverseString::id)
                                 .build(&StrConstOverload::reverseString));

        fns.push_back(rtl::type().member<StrConstOverload>()
                                 .methodConst<void>(cxx::type::StrConstOverload::fn::reverseString::id)
                                 .build(&StrConstOverload::reverseString));
    }
}

