
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include "reg_ids.h"
#include "reg_decls.h"

#include "StringMute.h"


namespace regs4::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<StrMute>(cxx::type::StrMute::id)
                                 .build());

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string_view>(cxx::type::StrMute::fn::revStrOverloadValCRef::id)
                                 .build(&StrMute::revStrOverloadValCRef));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<const std::string_view &>(cxx::type::StrMute::fn::revStrOverloadValCRef::id)
                                 .build(&StrMute::revStrOverloadValCRef));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<void>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(&StrMute::reverseString));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<const char *>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(&StrMute::reverseString));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(&StrMute::reverseString));

    /*  GCC here fails to automatically resolve the correct overloaded functor
        when both a lvalue reference and an rvalue overload exist.
        To disambiguate, explicitly cast the member function pointer.
    */  fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string &>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(static_cast<std::string(StrMute::*)(std::string&)>(&StrMute::reverseString)));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string &&>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(static_cast<std::string(StrMute::*)(std::string&&)>(&StrMute::reverseString)));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<const std::string &>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(static_cast<std::string(StrMute::*)(const std::string&)>(&StrMute::reverseString)));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string *>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(&StrMute::reverseString));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<const std::string *>(cxx::type::StrMute::fn::reverseString::id)
                                 .build(&StrMute::reverseString));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method(cxx::type::StrMute::fn::revStrConstRefArg::id)
                                 .build(&StrMute::revStrConstRefArg));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method(cxx::type::StrMute::fn::revStrRValueRefArg::id)
                                 .build(&StrMute::revStrRValueRefArg));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method(cxx::type::StrMute::fn::revStrNonConstRefArg::id)
                                 .build(&StrMute::revStrNonConstRefArg));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string_view &>(cxx::type::StrMute::fn::revStrOverloadRefAndCRef::id)
                                 .build(&StrMute::revStrOverloadRefAndCRef));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<const std::string_view &>(cxx::type::StrMute::fn::revStrOverloadRefAndCRef::id)
                                 .build(&StrMute::revStrOverloadRefAndCRef));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string_view>(cxx::type::StrMute::fn::revStrOverloadValRef::id)
                                 .build(&StrMute::revStrOverloadValRef));

        fns.push_back(rtl::type().member<StrMute>()
                                 .method<std::string_view &>(cxx::type::StrMute::fn::revStrOverloadValRef::id)
                                 .build(&StrMute::revStrOverloadValRef));
    }
}

