
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include "reg_ids.h"
#include "reg_decls.h"

#include "Complex.h"


namespace regs10::fn {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().function(cxx::fn::complex::getMagnitude::id)
                                 .build(&complex::getMagnitude));

        fns.push_back(rtl::type().function(cxx::fn::complex::setReal::id)
                                 .build(&complex::setReal));

        fns.push_back(rtl::type().function(cxx::fn::complex::setImaginary::id)
                                 .build(&complex::setImaginary));

        fns.push_back(rtl::type().function(cxx::fn::getComplexNumAsString::id)
                                 .build(&getComplexNumAsString));
    }
}

