/*****************************************************************************
 *                                                                           *
 *  clang-mirror Generated Reflection Surface                                *
 *                                                                           *
 *  This file is automatically generated by clang-mirror and represents      *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library (RTL).                                       *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection, enabling         *
 *  compiler checking and IDE integration.                                   *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *                                                                           *
 *  SPDX-License-Identifier: MIT                                             *
 *                                                                           *
 *****************************************************************************/


#include "reg_ids.h"
#include "reg_decls.h"

#include "Date.h"


namespace regs1::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<nsdate::Calender>(cxx::type::nsdate::Calender::id)
                                 .build());

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .methodStatic(cxx::type::nsdate::Calender::fn::resetMoveOpsCounter::id)
                                 .build(&nsdate::Calender::resetMoveOpsCounter));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .methodStatic(cxx::type::nsdate::Calender::fn::getMoveOpsCount::id)
                                 .build(&nsdate::Calender::getMoveOpsCount));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .methodStatic(cxx::type::nsdate::Calender::fn::create::id)
                                 .build(&nsdate::Calender::create));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .method(cxx::type::nsdate::Calender::fn::getSavedDate::id)
                                 .build(&nsdate::Calender::getSavedDate));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .method(cxx::type::nsdate::Calender::fn::getTheDate::id)
                                 .build(&nsdate::Calender::getTheDate));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .method(cxx::type::nsdate::Calender::fn::getSavedEvent::id)
                                 .build(&nsdate::Calender::getSavedEvent));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .method(cxx::type::nsdate::Calender::fn::getTheEvent::id)
                                 .build(&nsdate::Calender::getTheEvent));

        fns.push_back(rtl::type().member<nsdate::Calender>()
                                 .methodStatic(cxx::type::nsdate::Calender::fn::instanceCount::id)
                                 .build(&nsdate::Calender::instanceCount));
    }
}


namespace regs1::type1 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<nsdate::Date>(cxx::type::nsdate::Date::id)
                                 .build());

        fns.push_back(rtl::type().member<nsdate::Date>()
                                 .methodStatic(cxx::type::nsdate::Date::fn::instanceCount::id)
                                 .build(&nsdate::Date::instanceCount));

        fns.push_back(rtl::type().member<nsdate::Date>()
                                 .methodConst(cxx::type::nsdate::Date::fn::getAsString::id)
                                 .build(&nsdate::Date::getAsString));

        fns.push_back(rtl::type().member<nsdate::Date>()
                                 .method(cxx::type::nsdate::Date::fn::updateDate::id)
                                 .build(&nsdate::Date::updateDate));

        fns.push_back(rtl::type().member<nsdate::Date>()
                                 .constructor<unsigned int, unsigned int, unsigned int>().build());

        fns.push_back(rtl::type().member<nsdate::Date>()
                                 .constructor<const std::string &>().build());
    }
}


namespace regs1::type2 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<nsdate::Event>(cxx::type::nsdate::Event::id)
                                 .build());

        fns.push_back(rtl::type().member<nsdate::Event>()
                                 .methodStatic(cxx::type::nsdate::Event::fn::instanceCount::id)
                                 .build(&nsdate::Event::instanceCount));

        fns.push_back(rtl::type().member<nsdate::Event>()
                                 .method(cxx::type::nsdate::Event::fn::getEventDate::id)
                                 .build(&nsdate::Event::getEventDate));

        fns.push_back(rtl::type().member<nsdate::Event>()
                                 .method(cxx::type::nsdate::Event::fn::reset::id)
                                 .build(&nsdate::Event::reset));
    }
}

